edie ci.yaml2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,52 +11,113 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  fmt:
-    runs-on: "ubuntu-latest"
+ 
+    test-abi3:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      # If one platform fails, allow the rest to keep testing if `CI-no-fail-fast` label is present
+      fail-fast: ${{ !contains(github.event.pull_request.labels.*.name, 'CI-no-fail-fast') }}
+      matrix:
+        os: [ubuntu-latest, macos-latest, windows-latest]
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Set up Python ${{ matrix.python-version }}
+      - uses: actions/checkout@master
+      - name: Setup python
         uses: actions/setup-python@v4
         with:
-          python-version: "3.x"
+          python-version: 3.9
 
-      - run: pip install black
+      - uses: dtolnay/rust-toolchain@stable
 
-      - run: black --check .
+      - name: Install Rust aarch64-apple-darwin target
+        if: matrix.os == 'macos-latest'
+        run: rustup target add aarch64-apple-darwin
 
-  mypy:
-    runs-on: "ubuntu-latest"
-    steps:
-      - uses: actions/checkout@v3
+      - name: Build package
+        run: pip install -e .
 
-      - name: Set up Python ${{ matrix.python-version }}
+      - name: Build an abi3 wheel
+        shell: bash
+        run: |
+          set -e
+          cd rqrcode/rqrcode/
+          python --version
+          pip install -U wheel
+          python setup.py bdist_wheel --py-limited-api=cp39
+          ls -la dist/
+        env:
+          # https://github.com/actions/setup-python/issues/26
+          MACOSX_DEPLOYMENT_TARGET: 10.9
+
+      # Now we switch to a differnet Python version and ensure we can install
+      # the wheel we just built.
+      - name: Setup python
         uses: actions/setup-python@v4
         with:
-          python-version: "3.x"
+          python-version: "3.10"
 
-      - run: pip install nox
-
-      - run: nox -s mypy
-
-  pytest:
-    runs-on: "ubuntu-latest"
+      - name: Install abi3 wheel and run tests
+        shell: bash
+        run: |
+          set -e
+          cd rqrcode/
+          pip install -U wheel
+          python --version
+          pip install rqrcode/dist/rqrcode*.whl
+          python -c "rqrcode.qrcode_unicode("hello")"
+      - name: Run abi3audit
+        shell: bash
+        run: |
+          set -e
+          pip install abi3audit
+          cd rqrcode/
+          abi3audit rqrcode/dist/rqrcode*.whl
+  test-crossenv:
+    runs-on: ubuntu-latest
+    strategy:
+      # If one platform fails, allow the rest to keep testing if `CI-no-fail-fast` label is present
+      fail-fast: ${{ !contains(github.event.pull_request.labels.*.name, 'CI-no-fail-fast') }}
+      matrix:
+        platform: [
+          { target: "aarch64-unknown-linux-gnu", arch: "aarch64" },
+          { target: "armv7-unknown-linux-gnueabihf", arch: "armv7" },
+        ]
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
+      - uses: actions/checkout@master
+      - name: Build wheels
+        run: |
+          echo 'set -ex
+          curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
+          source ~/.cargo/env
+          rustup target add ${{ matrix.platform.target }}
+          # https://github.com/pypa/setuptools_scm/issues/707
+          git config --global --add safe.directory /io
+          cd rqrcode/rqrcode/
+          python3.9 -m pip install crossenv
+          python3.9 -m crossenv "/opt/python/cp39-cp39/bin/python3" --cc $TARGET_CC --cxx $TARGET_CXX --sysroot $TARGET_SYSROOT --env LIBRARY_PATH= --manylinux manylinux1 venv
+          . venv/bin/activate
+          build-pip install cffi wheel "setuptools>=62.4"
+          cross-expose cffi
+          pip install wheel
+          pip install -e ../../
+          python setup.py bdist_wheel --py-limited-api=cp37
+          ls -la dist/
+          ' > build-wheels.sh
+          docker run --rm -v "$PWD":/io -w /io messense/manylinux2014-cross:${{ matrix.platform.arch }} bash build-wheels.sh
+      - name: Install abi3 wheel and run tests
+        uses: uraimo/run-on-arch-action@v2.0.5
         with:
-          python-version: "3.x"
-
-      - name: Install Rust toolchain
-        uses: dtolnay/rust-toolchain@stable
-
-      - run: pip install nox
-
-      - run: nox -s test
-
-  build:
+          arch: ${{ matrix.platform.arch }}
+          distro: ubuntu20.04
+          dockerRunArgs: |
+            --volume "${PWD}/rqrcode:/rqrcode"
+          install: |
+            apt-get update
+            apt-get install -y --no-install-recommends python3 python3-dev python3-pip build-essential libffi-dev
+          run: |
+            cd /rqrcode
+            python3 --version
+            pip3 install rqrcode/dist/rqrcode*.whl
+            python3 -c "rqrcode.qrcode_unicode("hello")"
     name:  ${{ matrix.python-version }} ${{ matrix.platform.os }}-${{ matrix.platform.python-architecture }}
     runs-on: ${{ matrix.platform.os }}
     strategy:
@@ -111,23 +172,6 @@ jobs:
           PYTHON: ${{ matrix.python-version }}
         run: nox -s test-examples
 
-      - name: Test macOS universal2
-        if: matrix.platform.os == 'macos-latest' && !startsWith(matrix.python-version, 'pypy')
-        shell: bash
-        env:
-          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
-          MACOSX_DEPLOYMENT_TARGET: '10.9'
-          ARCHFLAGS: -arch x86_64 -arch arm64
-          PYO3_CROSS_LIB_DIR: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
-        run: |
-          cd examples/namespace_package
-          pip install wheel
-          python setup.py bdist_wheel
-          ls -l dist/
-          pip install --force-reinstall dist/namespace_package*_universal2.whl
-          cd -
-          python -c "from namespace_package import rust; assert rust.rust_func() == 14"
-          python -c "from namespace_package import python; assert python.python_func() == 15"
 
       - name: Test sdist vendor Rust crates
         shell: bash
@@ -135,164 +179,7 @@ jobs:
         env:
           CARGO_BUILD_TARGET: ${{ matrix.platform.rust-target }}
 
-  test-abi3:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      # If one platform fails, allow the rest to keep testing if `CI-no-fail-fast` label is present
-      fail-fast: ${{ !contains(github.event.pull_request.labels.*.name, 'CI-no-fail-fast') }}
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-    steps:
-      - uses: actions/checkout@master
-      - name: Setup python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.9
-
-      - uses: dtolnay/rust-toolchain@stable
-
-      - name: Install Rust aarch64-apple-darwin target
-        if: matrix.os == 'macos-latest'
-        run: rustup target add aarch64-apple-darwin
-
-      - name: Build package
-        run: pip install -e .
-
-      - name: Build an abi3 wheel
-        shell: bash
-        run: |
-          set -e
-          cd examples/rust_with_cffi/
-          python --version
-          pip install -U wheel
-          python setup.py bdist_wheel --py-limited-api=cp39
-          ls -la dist/
-        env:
-          # https://github.com/actions/setup-python/issues/26
-          MACOSX_DEPLOYMENT_TARGET: 10.9
-
-      # Now we switch to a differnet Python version and ensure we can install
-      # the wheel we just built.
-      - name: Setup python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.10"
-
-      - name: Install abi3 wheel and run tests
-        shell: bash
-        run: |
-          set -e
-          cd examples/
-          pip install -U wheel
-          python --version
-          pip install rust_with_cffi/dist/rust_with_cffi*.whl
-          python -c "from rust_with_cffi import rust; assert rust.rust_func() == 14"
-          python -c "from rust_with_cffi.cffi import lib; assert lib.cffi_func() == 15"
-
-      - name: Run abi3audit
-        shell: bash
-        run: |
-          set -e
-          pip install abi3audit
-          cd examples/
-          abi3audit rust_with_cffi/dist/rust_with_cffi*.whl
-
-  test-crossenv:
-    runs-on: ubuntu-latest
-    strategy:
-      # If one platform fails, allow the rest to keep testing if `CI-no-fail-fast` label is present
-      fail-fast: ${{ !contains(github.event.pull_request.labels.*.name, 'CI-no-fail-fast') }}
-      matrix:
-        platform: [
-          { target: "aarch64-unknown-linux-gnu", arch: "aarch64" },
-          { target: "armv7-unknown-linux-gnueabihf", arch: "armv7" },
-        ]
-    steps:
-      - uses: actions/checkout@master
-      - name: Build wheels
-        run: |
-          echo 'set -ex
-          curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
-          source ~/.cargo/env
-          rustup target add ${{ matrix.platform.target }}
-
-          # https://github.com/pypa/setuptools_scm/issues/707
-          git config --global --add safe.directory /io
-
-          cd examples/rust_with_cffi/
-          python3.9 -m pip install crossenv
-          python3.9 -m crossenv "/opt/python/cp39-cp39/bin/python3" --cc $TARGET_CC --cxx $TARGET_CXX --sysroot $TARGET_SYSROOT --env LIBRARY_PATH= --manylinux manylinux1 venv
-          . venv/bin/activate
-          build-pip install cffi wheel "setuptools>=62.4"
-          cross-expose cffi
-          pip install wheel
-          pip install -e ../../
-          python setup.py bdist_wheel --py-limited-api=cp37
-          ls -la dist/
-          ' > build-wheels.sh
-
-          docker run --rm -v "$PWD":/io -w /io messense/manylinux2014-cross:${{ matrix.platform.arch }} bash build-wheels.sh
-      - name: Install abi3 wheel and run tests
-        uses: uraimo/run-on-arch-action@v2.0.5
-        with:
-          arch: ${{ matrix.platform.arch }}
-          distro: ubuntu20.04
-          dockerRunArgs: |
-            --volume "${PWD}/examples:/examples"
-          install: |
-            apt-get update
-            apt-get install -y --no-install-recommends python3 python3-dev python3-pip build-essential libffi-dev
-          run: |
-            cd /examples
-            python3 --version
-            pip3 install rust_with_cffi/dist/rust_with_cffi*.whl
-            python3 -c "from rust_with_cffi import rust; assert rust.rust_func() == 14"
-            python3 -c "from rust_with_cffi.cffi import lib; assert lib.cffi_func() == 15"
-
-  test-cross:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Setup python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.8
-      - uses: dtolnay/rust-toolchain@stable
-      - name: Install cross
-        uses: taiki-e/install-action@v1
-        with:
-          tool: cross
-      - name: Build package
-        run: pip install -e .
-      - name: Build wheel using cross
-        shell: bash
-        env:
-          CARGO: cross
-          CARGO_BUILD_TARGET: aarch64-unknown-linux-gnu
-          PYO3_CROSS_LIB_DIR: /opt/python/cp38-cp38/lib
-        run: |
-          cd examples/namespace_package
-          docker build -t cross-pyo3:aarch64-unknown-linux-gnu .
-          python -m pip install wheel
-          python setup.py bdist_wheel --plat-name manylinux2014_aarch64
-          ls -la dist/
-      - uses: uraimo/run-on-arch-action@v2.1.1
-        name: Install built wheel
-        with:
-          arch: aarch64
-          distro: ubuntu20.04
-          dockerRunArgs: |
-            --volume "${PWD}/examples/namespace_package:/io"
-          install: |
-            apt-get update
-            apt-get install -y --no-install-recommends python3 python3-pip
-            pip3 install -U pip
-          run: |
-            pip3 install namespace_package --no-index --find-links /io/dist/ --force-reinstall
-            python3 -c "from namespace_package import rust; assert rust.rust_func() == 14"
-            python3 -c "from namespace_package import python; assert python.python_func() == 15"
-
-  test-zigbuild:
+ 
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -317,7 +204,7 @@ jobs:
         run: |
           mkdir -p $PYO3_CROSS_LIB_DIR
           docker cp -L $(docker create --rm quay.io/pypa/manylinux2014_aarch64:latest):/opt/python/cp38-cp38 /opt/python
-          cd examples/namespace_package
+          cd rqrcode/rqrcode
           python -m pip install wheel
           python setup.py bdist_wheel --plat-name manylinux2014_aarch64
           ls -la dist/
@@ -327,7 +214,7 @@ jobs:
           arch: aarch64
           distro: ubuntu20.04
           dockerRunArgs: |
-            --volume "${PWD}/examples/namespace_package:/io"
+            --volume "${PWD}/rqrcode/rqrcode:/io"
           install: |
             apt-get update
             apt-get install -y --no-install-recommends python3 python3-pip
@@ -337,7 +224,7 @@ jobs:
             python3 -c "from namespace_package import rust; assert rust.rust_func() == 14"
             python3 -c "from namespace_package import python; assert python.python_func() == 15"
 
-  test-cibuildwheel:
+
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
@@ -351,50 +238,9 @@ jobs:
           CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
           CIBW_BUILD_VERBOSITY: 1
         with:
-          package-dir: examples/namespace_package
+          package-dir: rqrcode/rqrcode
 
-  test-mingw:
-    runs-on: windows-latest
-    name:  ${{ matrix.python-version }} mingw-${{ matrix.arch }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include: [
-          { msystem: MINGW64, arch: x86_64, path: mingw64, rust_target: x86_64-pc-windows-gnu },
-          { msystem: MINGW32, arch: i686, path: mingw32, rust_target: i686-pc-windows-gnu }
-        ]
-    steps:
-      - uses: actions/checkout@v2
-      - name: Install MSys2 and dependencies
-        uses: msys2/setup-msys2@v2
-        with:
-          update: true
-          msystem: ${{ matrix.msystem }}
-          install: >-
-            git
-            mingw-w64-${{ matrix.arch }}-python
-            mingw-w64-${{ matrix.arch }}-python-pip
-            mingw-w64-${{ matrix.arch }}-openssl
-            mingw-w64-${{ matrix.arch }}-toolchain
 
-      - uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: stable-${{ matrix.rust_target }}
-
-      - name: Install test dependencies
-        shell: msys2 {0}
-        run: python -m pip install --upgrade nox pip wheel
-
-      - name: Create libpython symlink
-        shell: msys2 {0}
-        run: ln -s /${{ matrix.path }}/lib/libpython3.10.dll.a /${{ matrix.path }}/lib/libpython310.dll.a
-
-      - name: Test examples
-        shell: msys2 {0}
-        run: |
-          PATH="$PATH:/c/Users/runneradmin/.cargo/bin" nox -s test-mingw
-
-  test-emscripten:
     name: Test Emscripten
     runs-on: ubuntu-latest
     steps:
