ci.yaml21

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,58 +11,36 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-
-  test-crossenv:
-    runs-on: ubuntu-latest
+  build:
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 10
     strategy:
-      # If one platform fails, allow the rest to keep testing if `CI-no-fail-fast` label is present
-      fail-fast: ${{ !contains(github.event.pull_request.labels.*.name, 'CI-no-fail-fast') }}
+      fail-fast: false
       matrix:
-        platform: [
-          { target: "aarch64-unknown-linux-gnu", arch: "aarch64" },
-        ]
+        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
+        os: [ubuntu-18.04, macOS-latest, windows-latest]
+        include:
+          # pypy-3.7 on Mac OS currently fails trying to compile
+          # brotlipy. Moving pypy3 to only test linux.
+          - python-version: pypy-3.7
+            os: ubuntu-latest
+            experimental: false
     steps:
       - uses: actions/checkout@master
-      - name: Build wheels
-        run: |
-          echo 'set -ex
-          curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
-          source ~/.cargo/env
-          rustup target add ${{ matrix.platform.target }}
-          # https://github.com/pypa/setuptools_scm/issues/707
-          git config --global --add safe.directory /io
-          apt-get install tree
-          python3.9 -m pip install  pip==22.3.1
-          python3.9 -m pip install crossenv
-          python3.9 -m crossenv "/opt/python/cp39-cp39/bin/python3" --cc $TARGET_CC --cxx $TARGET_CXX --sysroot $TARGET_SYSROOT --env LIBRARY_PATH= --manylinux manylinux1 venv
-          . venv/bin/activate
-          build-pip install cffi wheel "setuptools>=62.4" setuptools-rust maturin
-          cross-expose cffi
-          pip install setuptools-rust
-          pip install wheel
-          pip list
-          # pip install -e ./
-          python setup.py bdist_wheel --py-limited-api=cp37
-          ls -la dist/
-          ' > build-wheels.sh
-          docker run --rm -v "$PWD":/io -w /io messense/manylinux2014-cross:${{ matrix.platform.arch }} bash build-wheels.sh
-      - name: Install abi3 wheel and run tests
-        uses: uraimo/run-on-arch-action@v2.0.5
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
         with:
-          arch: ${{ matrix.platform.arch }}
-          distro: ubuntu20.04
-          dockerRunArgs: |
-            --volume "${PWD}:/rqrcode"
-          install: |
-            apt-get update
-            apt-get install -y --no-install-recommends python3 python3-dev python3-pip build-essential libffi-dev tree
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies and Build wheels
           run: |
-            ls
-            pwd
-            # tree
-            python3 --version
-            pip3 install dist/rqrcode*.whl
-            python3 -c "import rqrcode; print(dir(rqrcode))"
-            #python3 -c "from rqrcode import rqrcode; rqrcode.qrcode_unicode('Hello')"
-
-  
+            echo 'set -ex
+            curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
+            source ~/.cargo/env
+            rustup target add ${{ matrix.platform.target }}
+            # https://github.com/pypa/setuptools_scm/issues/707
+            git config --global --add safe.directory /io
+            apt-get install tree
+            python3.9 -m pip install  pip==22.3.1
+            python3.9 -m pip install  cffi wheel "setuptools>=62.4" setuptools-rust maturin
+            pip list
+            python setup.py bdist_wheel 
